name: 'server'

on:
  push:
    branches: [main]
    paths:
      - 'apps/server/**'
      - '.github/workflow/server.yaml'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    defaults:
      run:
        working-directory: ./apps/server

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        working-directory: ./apps/server
        run: npm build
      - name: Test
        working-directory: ./apps/server
        run: npm test
